import type { UserConfig } from "@commitlint/types";

export default {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"type-enum": [
			2,
			"always",
			[
				"add",
				"breaking",
				"bugfix",
				"build",
				"chore",
				"ci",
				"config",
				"create",
				"delete",
				"deploy",
				"docs",
				"downgrade",
				"feat",
				"fix",
				"hotfix",
				"major",
				"merge",
				"minor",
				"patch",
				"perf",
				"refactor",
				"release",
				"remove",
				"revert",
				"security",
				"style",
				"test",
				"update",
				"upgrade",
				"wip",
			],
		],
		"subject-case": [2, "always", "sentence-case"],
	},
} as UserConfig;
